### ISSUE TITLE
Use .cifuzz-build directory as corpus location

### ISSUE THREAD

**Issue by patdhlk** [CodeIntelligenceTesting/cifuzz#891]
cifuzz creates and stores the corpus on bazel package level. However, the .cifuzz-build directory or any other build directory would be a better location. This pollutes the working directory and also would unnecessarily grow the `.gitignore` file. 

cifuzz version: 0.38.1
buildsystem: bazel
bazel version: 6.0.0

let me know if you need further information

**Comment by jochil** [comment]
Thanks for the feedback... we will take a look into that and keep you updated.

Theoretically the generated corpus should be located under `.cifuzz-corpus` and should be ignored by git.
The seed corpus (including the crashing inputs), on the other hand, should be part of the repository. We will check how it is handled differently in bazel and why

**Comment by adombeck** [comment]
That would be a non-trivial change. There are technical and conceptual reasons to store the corpus inside the Bazel package:

1. We include in the corpus in the `cc_fuzz_test` definition in the Bazel package: https://github.com/CodeIntelligenceTesting/cifuzz/blob/ac2135b57fd607aa76be34a4e9afdcefb6529732/examples/bazel/src/BUILD.bazel#L19
In Bazel, you can’t reach into other packages (including the top-level one) and grab arbitrary files. In order to still be able to access the corpus form within the package, the top-level package would need to contain `BUILD` file definitions for the corpus directory (e.g. `exports_files([".cifuzz-corpus"])`. 

2. Even more restrictive, even if you export files, you can’t `glob` a subset of them. So we would either need to add the entire `cifuzz-corpus` directory to the data of every fuzz test and pick the correct subdirectory at runtime (and live with the increased number of runfiles) or add one BUILD definition per subdirectory of `.cifuzz-corpus` to the top-level `BUILD` file. The latter is probably better and could be wrapped into a macro.

3. Monorepos tend to dislike files in top-level directories. If only the `//src/main/cpp/automotive_lib/...` part of the monorepo uses fuzzing, why should they have to pollute the top-level directory with fuzzing-specific files? 

The cleaner solution is probably to add a pattern to the top-level `.gitignore` file which ignores all cifuzz corpus directories in the project: https://github.com/CodeIntelligenceTesting/cifuzz/blob/ac2135b57fd607aa76be34a4e9afdcefb6529732/examples/bazel/.gitignore#L3

@patdhlk Does that work for you?
